'use client';

import { useState } from 'react';
import type { FormEvent } from 'react';
import { Button } from '@/components/ui/Button';
import { Field } from '@/components/ui/Field';
import { ProductVisual } from '@/components/ui/ProductVisual';
import { useCart } from '@/features/cart/CartProvider';
import { useI18n } from '@/features/i18n/I18nProvider';
import { categoryMessageKeys, variantMessageKeys } from '@/features/catalog/catalog-labels';
import type { Product } from '@/features/catalog/types';

export function ProductDetail({ product }: { product: Product }) { const { locale, t } = useI18n(); const { addItem } = useCart(); const [variantId, setVariantId] = useState(product.variants[0]?.id ?? 'signature'); const [addOnIds, setAddOnIds] = useState<string[]>([]); const [message, setMessage] = useState(''); const [deliveryDate, setDeliveryDate] = useState('2026-08-20'); const [added, setAdded] = useState(false); const variant = product.variants.find((item) => item.id === variantId); const addOns = product.addOns.filter((item) => addOnIds.includes(item.id)); const unitPrice = product.price + (variant?.priceDelta ?? 0); const name = locale === 'ar' ? product.nameAr ?? product.name : product.name; const description = locale === 'ar' ? product.descriptionAr ?? product.description : product.description; const delivery = product.delivery.startsWith('Same-day') ? t('sameDay') : t('nextDay'); function toggleAddOn(id: string) { setAddOnIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); } function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); addItem({ id: `${product.slug}-${variantId}-${[...addOnIds].sort().join('-') || 'none'}-${deliveryDate}`, productSlug: product.slug, productName: product.name, productNameAr: product.nameAr, tone: product.tone, unitPrice, quantity: 1, variantId: variant?.id, variantName: variant ? (locale === 'ar' ? t(variantMessageKeys[variant.id] ?? variant.name) : variant.name) : undefined, addOns, message: message.trim(), deliveryDate }); setAdded(true); }
  return <div className="product-detail"><div><ProductVisual tone={product.tone} label={`${name} visual`} /></div><div className="product-detail-copy"><p className="eyebrow">{t(categoryMessageKeys[product.category] ?? 'plants')} · {delivery}</p><h1>{name}</h1><p className="product-description">{description}</p><p className="product-price">{t('from')} {new Intl.NumberFormat(locale === 'ar' ? 'ar-EG' : 'en-EG', { style: 'currency', currency: 'EGP', maximumFractionDigits: 0 }).format(unitPrice / 100)}</p><form className="customization-form" onSubmit={submit}>{product.variants.length ? <fieldset><legend>{t('chooseSize')}</legend>{product.variants.map((item) => <label className="choice" key={item.id}><input type="radio" name="variant" value={item.id} checked={variantId === item.id} onChange={() => setVariantId(item.id)} /><span>{locale === 'ar' ? t(variantMessageKeys[item.id] ?? item.name) : item.name}{item.priceDelta ? ` · +${item.priceDelta / 100} EGP` : ''}</span></label>)}</fieldset> : null}{product.addOns.length ? <fieldset><legend>{t('extraThoughtful')}</legend>{product.addOns.map((item) => <label className="choice" key={item.id}><input type="checkbox" checked={addOnIds.includes(item.id)} onChange={() => toggleAddOn(item.id)} /><span>{locale === 'ar' && item.id === 'note' ? t('handwrittenNote') : locale === 'ar' && item.id === 'chocolate' ? t('darkChocolate') : locale === 'ar' && item.id === 'balloon' ? t('balloon') : item.name} · +{item.price / 100} EGP</span></label>)}</fieldset> : null}<Field label={t('deliveryDate')} type="date" min="2026-08-17" value={deliveryDate} onChange={(event) => setDeliveryDate(event.target.value)} required /><label className="field" htmlFor="message"><span>{t('giftNote')} <small>({t('optional')})</small></span><textarea id="message" maxLength={160} value={message} onChange={(event) => setMessage(event.target.value)} placeholder={t('notePlaceholder')} /></label><Button type="submit">{t('addToBag')} <span aria-hidden="true">↗</span></Button>{added ? <p className="added-note" role="status">{t('added')} <a href="/cart">{t('reviewBag')} ↗</a></p> : null}</form></div></div>; }
