'use client';

import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { useI18n } from '@/features/i18n/I18nProvider';
import { categories, occasions } from './data';
import { categoryMessageKeys, occasionMessageKeys } from './catalog-labels';
import { parseCatalogQuery, serializeCatalogQuery } from './catalog-utils';

export function CatalogToolbar() { const { t } = useI18n(); const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams(); const query = parseCatalogQuery(new URLSearchParams(searchParams.toString())); function update(key: 'search' | 'category' | 'occasion' | 'sort', value: string) { const next = { ...query, [key]: value || undefined }; const serialized = serializeCatalogQuery(next); router.push(`${pathname}${serialized ? `?${serialized}` : ''}`); } return <div className="catalog-toolbar"><label className="field toolbar-search"><span>{t('search')}</span><input value={query.search ?? ''} onChange={(event) => update('search', event.target.value)} placeholder={t('searchPlaceholder')} /></label><label className="field"><span>{t('category')}</span><select value={query.category ?? 'all'} onChange={(event) => update('category', event.target.value)}>{categories.map((category) => <option key={category} value={category}>{category === 'all' ? t('all') : t(categoryMessageKeys[category] ?? category)}</option>)}</select></label><label className="field"><span>{t('occasion')}</span><select value={query.occasion ?? 'all'} onChange={(event) => update('occasion', event.target.value)}>{occasions.map((occasion) => <option key={occasion} value={occasion}>{occasion === 'all' ? t('all') : t(occasionMessageKeys[occasion] ?? occasion)}</option>)}</select></label><label className="field"><span>{t('sort')}</span><select value={query.sort ?? 'recommended'} onChange={(event) => update('sort', event.target.value)}><option value="recommended">{t('recommended')}</option><option value="newest">{t('newest')}</option><option value="price-asc">{t('priceAsc')}</option><option value="price-desc">{t('priceDesc')}</option></select></label></div>; }
