import type { Product } from './types';

export const products: Product[] = [
  { slug: 'rose-hour', name: 'Rose Hour', nameAr: 'ساعة الورد', description: 'Soft garden roses', descriptionAr: 'ورود حدائق ناعمة لرسالة لا تحتاج إلى كلمات إضافية.', category: 'hand-bouquet', occasions: ['birthday', 'love'], price: 12000, tone: '#bc6d63', inventory: 8, delivery: 'Same-day in Cairo and Alexandria', createdAt: '2026-01-02', variants: [{ id: 'classic', name: 'Classic', priceDelta: 0 }, { id: 'generous', name: 'Generous', priceDelta: 4500 }], addOns: [{ id: 'note', name: 'Handwritten note', price: 500 }, { id: 'chocolate', name: 'Dark chocolate', price: 1800 }] },
  { slug: 'green-morning', name: 'Green Morning', nameAr: 'صباح أخضر', description: 'A leafy vase arrangement', descriptionAr: 'تنسيق أخضر في مزهرية يحمل هدوء نافذة مفتوحة.', category: 'vase-arrangement', occasions: ['thank-you', 'new-home'], price: 18000, tone: '#6f8b73', inventory: 4, delivery: 'Next-day delivery', createdAt: '2026-03-02', variants: [{ id: 'single', name: 'Single vase', priceDelta: 0 }, { id: 'double', name: 'Double vase', priceDelta: 7000 }], addOns: [{ id: 'note', name: 'Handwritten note', price: 500 }] },
  { slug: 'sunlit-stems', name: 'Sunlit Stems', nameAr: 'سيقان مضيئة', description: 'Golden stems and a little movement', descriptionAr: 'سيقان ذهبية مليئة بالحيوية ليوم مشرق.', category: 'hand-bouquet', occasions: ['birthday', 'congratulations'], price: 14500, tone: '#d6b56d', inventory: 7, delivery: 'Same-day in Cairo and Alexandria', createdAt: '2026-02-14', variants: [], addOns: [{ id: 'note', name: 'Handwritten note', price: 500 }, { id: 'balloon', name: 'Celebration balloon', price: 1200 }] },
  { slug: 'terracotta-love', name: 'Terracotta Love', nameAr: 'حب بلون الطين', description: 'Warm ranunculus and a sculptural wrap', descriptionAr: 'أزهار رانانكيولوس دافئة وتغليف أنيق لمبادرة من القلب.', category: 'hand-bouquet', occasions: ['love'], price: 22000, tone: '#d19a82', inventory: 3, delivery: 'Next-day delivery', createdAt: '2026-02-01', variants: [], addOns: [{ id: 'chocolate', name: 'Dark chocolate', price: 1800 }] },
  { slug: 'quiet-orchid', name: 'Quiet Orchid', nameAr: 'أوركيد هادئ', description: 'An elegant orchid plant', descriptionAr: 'نبتة أوركيد أنيقة تحافظ على الشعور حيّاً.', category: 'plants', occasions: ['new-home', 'thank-you'], price: 26000, tone: '#b7a8c7', inventory: 2, delivery: 'Next-day delivery', createdAt: '2026-01-20', variants: [{ id: 'small', name: 'Small', priceDelta: 0 }, { id: 'large', name: 'Large', priceDelta: 8000 }], addOns: [] },
  { slug: 'wild-meadow', name: 'Wild Meadow', nameAr: 'مرج بري', description: 'Loose seasonal color', descriptionAr: 'ألوان موسمية حرة، كأنها جُمعت من نزهة صباحية.', category: 'vase-arrangement', occasions: ['congratulations'], price: 19500, tone: '#9aaf83', inventory: 6, delivery: 'Next-day delivery', createdAt: '2026-03-10', variants: [], addOns: [{ id: 'note', name: 'Handwritten note', price: 500 }] },
  { slug: 'little-thanks', name: 'Little Thanks', nameAr: 'شكر صغير', description: 'A petite posy', descriptionAr: 'باقة صغيرة للأشخاص الذين يجعلون أيامنا أجمل.', category: 'hand-bouquet', occasions: ['thank-you'], price: 8500, tone: '#e2b5a6', inventory: 10, delivery: 'Same-day in Cairo and Alexandria', createdAt: '2026-01-09', variants: [], addOns: [{ id: 'note', name: 'Handwritten note', price: 500 }] },
  { slug: 'citrus-cloud', name: 'Citrus Cloud', nameAr: 'سحابة حمضيات', description: 'A light, fragrant arrangement', descriptionAr: 'تنسيق خفيف وعطِر بلمسة منعشة.', category: 'vase-arrangement', occasions: ['birthday'], price: 16000, tone: '#e4c57b', inventory: 5, delivery: 'Next-day delivery', createdAt: '2026-02-28', variants: [], addOns: [] },
];

export const categories = ['all', 'hand-bouquet', 'vase-arrangement', 'plants', 'gift-boxes', 'sympathy'];
export const occasions = ['all', 'birthday', 'love', 'thank-you', 'new-home', 'congratulations', 'sympathy'];
