import type { BlogPost } from './types';

export const localPosts: BlogPost[] = [
  {
    id: '90000000-0000-4000-8000-000000000001',
    slug: 'how-flower-delivery-works',
    type: 'post',
    cityCode: null,
    titleEn: 'How flower delivery works in Egypt',
    titleAr: 'كيف تعمل خدمة توصيل الزهور في مصر',
    excerptEn: 'Same-day windows, city coverage, and what to expect when your bouquet arrives.',
    excerptAr: 'نوافذ التوصيل في نفس اليوم، تغطية المدن، وما يمكن توقعه عند وصول باقتك.',
    contentEn: '<p>Ordering flowers online in Egypt is simpler than it looks. Pick your city, choose a delivery date and window, and we handle the rest.</p><p>Greater Cairo and Alexandria offer same-day delivery before the afternoon cutoff. Other cities are served next day.</p>',
    contentAr: '<p>طلب الزهور أونلاين في مصر أسهل مما يبدو. اختر مدينتك، وحدد تاريخ ووقت التوصيل، ونحن نتولى الباقي.</p><p>القاهرة الكبرى والإسكندرية توفران توصيل نفس اليوم قبل موعد القطع بعد الظهر. باقي المدن تُخدم في اليوم التالي.</p>',
    category: 'guides',
    published: true,
    publishedAt: '2026-08-08T10:00:00.000Z',
    createdAt: '2026-08-08T10:00:00.000Z',
    updatedAt: '2026-08-08T10:00:00.000Z',
  },
  {
    id: '90000000-0000-4000-8000-000000000002',
    slug: 'keep-roses-fresh',
    type: 'post',
    cityCode: null,
    titleEn: '5 tips for keeping roses fresh longer',
    titleAr: '5 نصائح لإبقاء الورد طازجاً لفترة أطول',
    excerptEn: 'Cut stems, fresh water, cool corners: the small habits that extend a bouquet’s life.',
    excerptAr: 'قص السيقان، ماء نظيف، زاوية باردة: عادات صغيرة تطيل عمر الباقة.',
    contentEn: '<p>Fresh roses can easily last a week with a little care.</p><ul><li>Trim the stems at an angle every two days.</li><li>Change the water and rinse the vase.</li><li>Keep the bouquet away from direct sun.</li></ul>',
    contentAr: '<p>يمكن للورد الطازج أن يعيش أسبوعاً بسهولة مع قليل من العناية.</p><ul><li>قص السيقان بزاوية كل يومين.</li><li>غيّر الماء واغسل المزهرية.</li><li>أبعد الباقة عن الشمس المباشرة.</li></ul>',
    category: 'care',
    published: true,
    publishedAt: '2026-08-12T10:00:00.000Z',
    createdAt: '2026-08-12T10:00:00.000Z',
    updatedAt: '2026-08-12T10:00:00.000Z',
  },
  {
    id: '90000000-0000-4000-8000-000000000003',
    slug: 'sympathy-flowers-etiquette',
    type: 'post',
    cityCode: null,
    titleEn: 'Sympathy flowers: etiquette and timing',
    titleAr: 'زهور التعازي: الآداب والتوقيت',
    excerptEn: 'When to send, what to choose, and how to word the card.',
    excerptAr: 'متى ترسل، وماذا تختار، وكيف تصوغ البطاقة.',
    contentEn: '<p>White and soft-hued arrangements are the classic choice for sympathy. Send as soon as you learn the news.</p>',
    contentAr: '<p>الترتيبات البيضاء والهادئة هي الخيار الكلاسيكي للتعازي. أرسل فور معرفتك بالخبر.</p>',
    category: 'occasions',
    published: true,
    publishedAt: '2026-08-16T10:00:00.000Z',
    createdAt: '2026-08-16T10:00:00.000Z',
    updatedAt: '2026-08-16T10:00:00.000Z',
  },
  {
    id: '90000000-0000-4000-8000-000000000004',
    slug: 'same-day-flower-delivery-cairo',
    type: 'city',
    cityCode: 'greater-cairo',
    titleEn: 'Same-day flower delivery in Cairo',
    titleAr: 'توصيل زهور في نفس اليوم في القاهرة',
    excerptEn: 'Fresh bouquets delivered across Greater Cairo the same day you order.',
    excerptAr: 'باقات طازجة تُوصَّل في جميع أنحاء القاهرة الكبرى في نفس يوم الطلب.',
    contentEn: '<p>Greater Cairo is our flagship same-day city. Order before the afternoon cutoff and your bouquet arrives in a chosen window.</p>',
    contentAr: '<p>القاهرة الكبرى هي مدينتنا الرئيسية للتوصيل في نفس اليوم. اطلب قبل موعد القطع بعد الظهر وستصل باقتك في الوقت الذي اخترته.</p>',
    category: 'delivery',
    published: true,
    publishedAt: '2026-08-14T10:00:00.000Z',
    createdAt: '2026-08-14T10:00:00.000Z',
    updatedAt: '2026-08-14T10:00:00.000Z',
  },
  {
    id: '90000000-0000-4000-8000-000000000005',
    slug: 'flower-delivery-alexandria',
    type: 'city',
    cityCode: 'alexandria',
    titleEn: 'Flower delivery in Alexandria',
    titleAr: 'توصيل الزهور في الإسكندرية',
    excerptEn: 'Same-day bouquets across the coastal city.',
    excerptAr: 'باقات في نفس اليوم في جميع أنحاء المدينة الساحلية.',
    contentEn: '<p>Alexandria enjoys same-day delivery across the coastal city, including Raml and Maamoura.</p>',
    contentAr: '<p>تتمتع الإسكندرية بتوصيل نفس اليوم في جميع أنحاء المدينة الساحلية، بما في ذلك الرمل والمعمورة.</p>',
    category: 'delivery',
    published: true,
    publishedAt: '2026-08-15T10:00:00.000Z',
    createdAt: '2026-08-15T10:00:00.000Z',
    updatedAt: '2026-08-15T10:00:00.000Z',
  },
];
