-- First-party product analytics events.
-- This is intentionally a narrow, server-validated event table rather than a
-- browser analytics SDK: Workers bundle size stays flat and no PII is stored.
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in (
    'product_view', 'add_to_cart', 'checkout_start', 'checkout_complete',
    'order_placed', 'search_performed', 'personalization_impression',
    'personalization_click'
  )),
  path text not null default '',
  locale text not null default 'en' check (locale in ('en', 'ar', 'fr')),
  product_slug text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_name_created_idx
  on public.analytics_events(event_name, created_at desc);
create index if not exists analytics_events_product_created_idx
  on public.analytics_events(product_slug, created_at desc)
  where product_slug is not null;

alter table public.analytics_events enable row level security;
drop policy if exists "deny all" on public.analytics_events;
create policy "deny all" on public.analytics_events
  for all to anon, authenticated using (false) with check (false);
revoke all on public.analytics_events from public, anon, authenticated;
grant insert, select on public.analytics_events to service_role;
